Add functions
strange-v/MHZ19 pull request #4
Opened 2018-09-06 10:50 UTC by PhantomVl

It is necessary to supplement the management teams with:
1. getMinCO2x24
2. setAccuracy
3. calibrateZero
4. calibrateSpan
5. setAutoCalibration

2018-09-07 17:08 UTC, strange-v commented
Hello.
Great functionality, could you please fix formatting a bit (curly brackets from the new line, spacing, etc) it is easier when all code has more or less the same formatting. Also, I've added a few questions about ranges due to lack of information.

2018-09-07 17:09 UTC, strange-v requested changes
Hello.
Great functionality, could you please fix formatting a bit (curly brackets from the new line, spacing, etc) it is easier when all code has more or less the same formatting. Also, I've added a few questions about ranges due to lack of information.

2018-09-07 17:09 UTC, strange-v commented on MHZ19.cpp
> +MHZ19_RESULT MHZ19::setAccuracy(MHZ19_MEASUREMENT _acc)
Probably name setRange is better here (word "range" is used in the datasheet).
Please rename argument too (could be "range", without underscore because it is for private properties of a class).

2018-09-07 17:09 UTC, strange-v commented on MHZ19.cpp
> +		  case PPM1000:
Could you please share your information about available ranges? According to the datasheet only two ranges available: 2000 ppm and 5000 ppm.
Also, the command has to be 0x99.

2018-09-07 17:09 UTC, strange-v commented on MHZ19.cpp
> +	for (int i = 0; i < 9; i++) {
Not needed because we have command memset below.

2018-09-07 17:09 UTC, strange-v commented on MHZ19.cpp
> +	_result = receiveResponse(&_response);
Again, according to the chinese datasheet, this command doesn't have any response. Have you tested it on MH-Z19 and MH-Z19B?

2018-09-07 17:09 UTC, strange-v commented on MHZ19.cpp
> +	cmd_3 = (uint8_t)(ppm/256);
Please use static_cast

2018-09-07 17:09 UTC, strange-v commented on MHZ19.cpp
> +	cmd_4 = (uint8_t)(ppm%256);
static_cast

2018-09-07 17:09 UTC, strange-v commented on MHZ19.h
> +enum MHZ19_MEASUREMENT {
MHZ19_RANGE

2018-09-07 17:09 UTC, strange-v commented on MHZ19.cpp
> +	if (mode) {
Please move curly bracket to the new line

2018-09-07 17:09 UTC, strange-v commented on MHZ19.cpp
> +	} else {
Please move curly bracket to the new line

2018-09-07 17:09 UTC, strange-v commented on MHZ19.cpp
> +			sendCommand(0x86,0x00,0x00,0x00,0x07,0xD0);
Probably it is better to do nothing by default, just do not calibrate sensor at all.

2018-09-07 17:09 UTC, strange-v commented on MHZ19.cpp
> +	if( ppm < 1000 )	return;
if (ppm < 1000) return;

2018-09-08 08:10 UTC, PhantomVl commented on MHZ19.cpp
> +		  case PPM1000:
https://wiki.iarduino.ru/file/CO2MH-Z19B-kit.pdf

2018-09-08 08:24 UTC, PhantomVl commented on MHZ19.cpp
> +MHZ19_RESULT MHZ19::setAccuracy(MHZ19_MEASUREMENT _acc)
I'm not so good at programming. If you make an aesthetically beautiful code from what I have proposed, I will be happy.
> setAccuracy OR setRange
To my regret, when changing the measuring range, the measurement accuracy changes.

2018-09-08 08:35 UTC, PhantomVl commented on MHZ19.cpp
> +	for (int i = 0; i < 9; i++) {
I ran into that problem on my debug Board when the memory allocated is not always clean. (ESP32)

2018-09-08 08:36 UTC, PhantomVl commented on MHZ19.cpp
> +	_result = receiveResponse(&_response);
I checked on the sensor brand MH-Z19B.

2018-09-08 12:06 UTC, strange-v commented on MHZ19.cpp
> +MHZ19_RESULT MHZ19::setAccuracy(MHZ19_MEASUREMENT _acc)
> To my regret, when changing the measuring range, the measurement accuracy changes.
Yes, ADC has some predefined resolution, let say 10 bit, so for the range from 0 to 2000 one step is 1.95 but for 0-5000 one step is 4.88.

2018-09-08 12:08 UTC, strange-v approved these changes

2018-09-08 12:09 UTC, merged